CREATE DATABASE OlaMundo;

USE OlaMundo;

CREATE TABLE Exemplo(
	ID INT NOT NULL IDENTITY,
	Nome VARCHAR(50)
);

ALTER TABLE Exemplo
	ADD CONSTRAINT PK_Exemplo PRIMARY KEY (ID);

ALTER TABLE Exemplo
	ADD DataNascimento DATE;

ALTER TABLE Exemplo
	DROP COLUMN DataNascimento;

CREATE TABLE Tabela2(
	ID INT NOT NULL IDENTITY PRIMARY KEY,
	Telefone VARCHAR(20) NOT NULL,
	ID_EXEMPLO INT NOT NULL,
	FOREIGN KEY(ID_Exemplo) REFERENCES Exemplo(ID)
);

DROP TABLE Tabela2;
DROP TABLE Exemplo;

USE master;
DROP DATABASE OlaMundo;
