use master;
drop database NotaFiscal;

CREATE DATABASE NotaFiscal;
USE NotaFiscal;

CREATE TABLE Produto(
	Codigo VARCHAR(15) NOT NULL PRIMARY KEY,
	Descricao VARCHAR(100) NOT NULL,
	Cfop VARCHAR(15) NOT NULL,
	Unidade VARCHAR(15) NOT NULL,
	Peso VARCHAR(5) NOT NULL,
	Cst VARCHAR(5) NOT NULL,
	Ncm VARCHAR(10) NOT NULL,
	Preco MONEY NOT NULL,
	PorcentIcms VARCHAR(3) NOT NULL
);

CREATE TABLE Nota(
	Nro VARCHAR(50) NOT NULL PRIMARY KEY,
	Serie VARCHAR(50) NOT NULl,
	-- PRIMARY KEY (Nro, Serie),
	CodOperacao VARCHAR(50) NOT NULL,
	ChaveAcesso VARCHAR(100) NOT NULL,
	NaturezaOperacao VARCHAR(50) NOT NULL,
	DataOperacao DATETIME NOT NULL,
	DadosAds VARCHAR(100) NOT NULL,
	CodigoProduto VARCHAR(15) NOT NULL,
	FOREIGN KEY(CodigoProduto) REFERENCES Produto(Codigo)
);

CREATE TABLE Fatura(
	NroNota VARCHAR(50) NOT NULL,
	FOREIGN KEY(NroNota) REFERENCES Nota(Nro),
	DataVence DATETIME NOT NULL,
	Valor MONEY NOT NULL
);

CREATE TABLE Imposto(
	NroNota VARCHAR(50) NOT NULL,
	FOREIGN KEY(NroNota) REFERENCES Nota(Nro),
	Nome VARCHAR(15) NOT NULL,
	BaseCalculo VARCHAR(50) NOT NULL,
	Valor MONEY NOT NULL,
	Desconto MONEY NOT NULL
);

CREATE TABLE Transportadora(
	Cnpj VARCHAR(15) NOT NULL,
	NroNota VARCHAR(50) NOT NULL PRIMARY KEY,
	--PRIMARY KEY (Cnpj, NroNota),
	FOREIGN KEY(NroNota) REFERENCES Nota(Nro),
	InscEstadual VARCHAR(50) NOT NULL,
	RazaoSocial VARCHAR(50) NOT NULL
	
);

CREATE TABLE Endereco (
	Cep VARCHAR(15) NOT NULL,
	Logradouro VARCHAR(50) NOT NULL,
	Numero VARCHAR(10) NOT NULL,
	Bairro VARCHAR(50) NOT NULL,
	Cidade VARCHAR(50) NOT NULL,
	Estado VARCHAR(50) NOT NULL,
	NroNota VARCHAR(50) NOT NULL PRIMARY KEY,
	--PRIMARY KEY (Cep, NroNota),
	FOREIGN KEY(NroNota) REFERENCES Transportadora(NroNota)
);

CREATE TABLE Cliente(
	Cnpj VARCHAR(15) NOT NULL PRIMARY KEY,
	RazaoSocial VARCHAR(50) NOT NULL,
	InscEstadual VARCHAR(50) NOT NULL,
	NroNota VARCHAR(50) NOT NULL,
	FOREIGN KEY(NroNota) REFERENCES Endereco(NroNota)
);

CREATE TABLE Empresa(
	Cnpj VARCHAR(15) NOT NULL PRIMARY KEY,
	RazaoSocial VARCHAR(50) NOT NULL,
	InscEstadual VARCHAR(50) NOT NULL,
	Telefone VARCHAR(15) NOT NULL,
	ProtocoloNfe VARCHAR(50) NOT NULL,
	NroNota VARCHAR(50) NOT NULL,
	FOREIGN KEY(NroNota) REFERENCES Endereco(NroNota)
);
